### PR TITLE
Commentary

### PR DESCRIPTION
**Pull request by sonofmun**
Commentary type added.
Unit testing finished.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
YEAHHHHH !

**Comment by sonofmun** [comment]
Should probably squash and merge (if everything passes).

**Comment by PonteIneptique** [comment]
I'll review, you'll squash and merge

**Comment by sonofmun** [comment]
Is that typical etiquette? That a squash and merge is done by the person who PRs?

**Comment by PonteIneptique** [comment]
If a reviewer approves, there is no issue with that.
I am afraid that if I squash myself, you would not be credited by git :/

**Comment by sonofmun** [comment]
NOOOO. Must....receive....credit!

**Comment by PonteIneptique** [comment]
You're good to squash :)

**Comment by sonofmun** [comment]
I love squashing!
HERE I GO!

**Pull request merged**
