### PR TITLE
Fixed the test for empty references so that it only finds empties whe…

### PR DESCRIPTION
**Pull request by sonofmun**
…re they actually occur.

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Great :) 
If you think you could do that, I'd be happy to see a fix for https://github.com/Capitains/MyCapytain/issues/163 and https://github.com/Capitains/MyCapytain/issues/162 for the next master bump ? :)

**Comment by sonofmun** [comment]
I will take a look at those as well. Maybe this afternoon, but I will have to see how the day goes.

**Comment by sonofmun** [comment]
Should they be added to this PR as well since (I assume) master builds every time something is merged?

**Comment by PonteIneptique** [comment]
Nop, pypi is updated when I do a github release :)

**Pull request merged**
