### PR TITLE
Changes to future branch for compatibility with rdflib 6.2.0

### PR DESCRIPTION
**Pull request by sonofmun**

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Crap, could you commit also the new tests that run on Github CI as well ? :/

**Comment by PonteIneptique** [comment]
they are on the dev Branch

**Comment by sonofmun** [comment]
That looks bad @PonteIneptique . I think that failing on 3.6 is expected since, if I recall correctly rdflib now is specifically not compatible with 3.6. But the other operations were simply cancelled.

**Comment by PonteIneptique** [comment]
Let me try something out ;)

**Comment by PonteIneptique** [comment]
I removed 3.6 (EOL) and 3.7 (Close to EOL)

**Comment by PonteIneptique** [comment]
https://devguide.python.org/versions/

**Comment by sonofmun** [comment]
Aha!

**Comment by PonteIneptique** [comment]
Merged !

**Comment by sonofmun** [comment]
Woohoo!

**Pull request merged**
