### PR TITLE
Changed some return typing declarations from 'object' to 'Collection'

### PR DESCRIPTION
**Pull request by sonofmun**
This is more generalizable and should avoid some unnecessary typing warnings down the line

### CODE REVIEW

**Comment by PonteIneptique** [comment]
Actually, why don't you use `Collection` ?

**Comment by sonofmun** [comment]
Because I think that importing Collection into the resolver would cause a circular import.

**Comment by PonteIneptique** [comment]
Damn, I never saw you answer ?

For typing purposes, you can do, at the top level of the package 

```python
FOR_TYPING = 1
if FOR_TYPING == 0:
    # imports that would cause circular import


def fn(something: str) -> "ClassThatIsCircularlyImported": # Quotes are important :)
```

**Comment by sonofmun** [comment]
@PonteIneptique That seems to work.

**Pull request merged**
