### PR TITLE
Stray print

### PR DESCRIPTION
**Pull request by sonofmun**
PRing to master since this needs to be fixed.

### CODE REVIEW

**Comment by sonofmun** [comment]
I will let you do the release.

**Comment by sonofmun** [comment]
Doesn't it build automatically when you do a release? Or do I need to do something else? PyPi is still showing 2.0.8.

**Comment by PonteIneptique** [comment]
Uploading MyCapytain-2.0.9.tar.gz
100%|██████████| 47.3k/47.3k
Give it some time :)

**Comment by sonofmun** [comment]
Time? But I want it now!

**Pull request merged**
