### PR TITLE
Fix problem with get_cts_property

### PR DESCRIPTION
**Pull request by sonofmun**
See #193

### CODE REVIEW

**Comment by sonofmun** [comment]
Hmm. This errored because Travis errored while trying to install the requirements for Python 3.4.5. The problem is that LXML requires Python 3.5 or later. This means either 3.4.5 need to be removed from testing or LXML needs to be downgraded (probably the former). I can make this change in the yml file or the requirements.txt file once you let me know which should be changed.

**Comment by sonofmun** [comment]
And I guess I need to write a test for this as well. I will do that presently.

**Comment by PonteIneptique** [comment]
I'd remove 3.4.5 personnaly, but I'd like @balmas approval for this one

**Comment by sonofmun** [comment]
Coverage is your friend!

**Comment by PonteIneptique** [comment]
Gentle warning to @zfletch

**Comment by zfletch** [comment]
@PonteIneptique thanks for the heads up. Perseids is currently using Python 3.4, but all dependencies are locked, so this shouldn't immediately affect us. I'll make sure to update to 3.5 the next time I update Capitains.

**Comment by PonteIneptique** [comment]
;) Happy to be helpful

**Pull request merged**
